<?php

namespace OpenSoutheners\LaravelApiable\Tests\Documentation;

use Illuminate\Support\Facades\File;
use OpenSoutheners\LaravelApiable\Tests\Fixtures\Controllers\CommentsController;
use OpenSoutheners\LaravelApiable\Tests\Fixtures\Controllers\PostsController;
use OpenSoutheners\LaravelApiable\Tests\TestCase;

class ApiableTypesCommandTest extends TestCase
{
    private string $tempPath;

    protected function setUp(): void
    {
        parent::setUp();
        $this->tempPath = sys_get_temp_dir().'/apiable-types-test-'.uniqid().'/api-schema.ts';
    }

    protected function tearDown(): void
    {
        if (is_dir(dirname($this->tempPath))) {
            File::deleteDirectory(dirname($this->tempPath));
        }

        parent::tearDown();
    }

    protected function defineRoutes($router): void
    {
        $router->middleware('auth:sanctum')->group(function () use ($router) {
            $router->get('posts', [PostsController::class, 'index']);
            $router->get('posts/{post}', [PostsController::class, 'show']);
        });

        $router->get('comments', [CommentsController::class, 'index']);
        $router->post('comments', [CommentsController::class, 'store']);
    }

    public function test_writes_the_generated_schema_file(): void
    {
        $this->artisan('apiable:types', ['--path' => $this->tempPath])->assertExitCode(0);

        $this->assertFileExists($this->tempPath);

        $contents = File::get($this->tempPath);

        $this->assertStringContainsString('// generated by apiable:types — do not edit', $contents);
        $this->assertStringContainsString('export interface EndpointSchema {', $contents);
        $this->assertStringContainsString('export const apiSchema = {', $contents);
        $this->assertStringContainsString("'label': {", $contents);
        $this->assertStringContainsString("'post': {", $contents);
    }

    public function test_only_option_restricts_output_to_matching_resources(): void
    {
        $this->artisan('apiable:types', [
            '--path' => $this->tempPath,
            '--only' => ['posts*'],
        ])->assertExitCode(0);

        $contents = File::get($this->tempPath);

        $this->assertStringContainsString("'post': {", $contents);
        $this->assertStringNotContainsString("'label': {", $contents);
    }

    public function test_exclude_option_drops_matching_resources(): void
    {
        $this->artisan('apiable:types', [
            '--path' => $this->tempPath,
            '--exclude' => ['posts*'],
        ])->assertExitCode(0);

        $contents = File::get($this->tempPath);

        $this->assertStringNotContainsString("'post': {", $contents);
        $this->assertStringContainsString("'label': {", $contents);
    }

    public function test_generated_output_has_balanced_braces_brackets_and_generics(): void
    {
        $this->artisan('apiable:types', ['--path' => $this->tempPath])->assertExitCode(0);

        $contents = File::get($this->tempPath);

        $this->assertSame(substr_count($contents, '{'), substr_count($contents, '}'));
        $this->assertSame(substr_count($contents, '['), substr_count($contents, ']'));
        $this->assertSame(substr_count($contents, '<'), substr_count($contents, '>'));
    }
}
