name: pint

on: [ push, pull_request ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    name: Laravel Pint

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: pint

      - name: Run analysis
        run: pint
