name: pint

on: [ push, pull_request ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    name: Laravel Pint

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: laravel/pint

      - name: Run analysis
        run: pint
