name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get release info
        id: query-release-info
        uses: release-flow/keep-a-changelog-action@v2
        with:
          command: query
          version: latest

      - name: Publish to Github releases
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.query-release-info.outputs.release-notes }}
          # TODO: Check PR https://github.com/softprops/action-gh-release/pull/304
          # make_latest: ${{ $GITHUB_REF_NAME == 'main' && true || false }}
          # TODO: Workaround for the above (semi-automatic workflow when non main releases):
          # FIXME: See https://github.com/open-southeners/laravel-apiable/actions/runs/4016588356
          # draft: ${{ $GITHUB_REF_NAME != 'main' && true || false }}
          # prerelease: true
          # files: '*.vsix'