<?php

namespace OpenSoutheners\LaravelApiable\Tests\Documentation\Exporters;

use OpenSoutheners\LaravelApiable\Documentation\Exporters\TypeScriptSchemaExporter;
use OpenSoutheners\LaravelApiable\Tests\TestCase;

class TypeScriptSchemaExporterTest extends TestCase
{
    public function test_emits_generated_header_comment(): void
    {
        $exporter = new TypeScriptSchemaExporter;

        $output = $exporter->export([]);

        $this->assertStringStartsWith('// generated by apiable:types — do not edit', $output);
    }

    public function test_emits_the_frozen_endpoint_schema_interface(): void
    {
        $exporter = new TypeScriptSchemaExporter;

        $output = $exporter->export([]);

        $this->assertStringContainsString('export interface EndpointSchema {', $output);
        $this->assertStringContainsString('resource: string;', $output);
        $this->assertStringContainsString('path: string;', $output);
        $this->assertStringContainsString(
            "filters: Record<string, { operators: Array<'equal' | 'not_equal' | 'like' | 'not_like' | 'gt' | 'gte' | 'lt' | 'lte' | 'scope'>; values?: string[] }>;",
            $output
        );
        $this->assertStringContainsString('sorts: string[];', $output);
        $this->assertStringContainsString('includes: string[];', $output);
        $this->assertStringContainsString('fields: Record<string, string[]>;', $output);
        $this->assertStringContainsString('appends: Record<string, string[]>;', $output);
        $this->assertStringContainsString('defaultSort?: string;', $output);
        $this->assertStringContainsString('defaultFilters?: Record<string, string>;', $output);
    }

    public function test_emits_an_empty_api_schema_const_when_given_no_resources(): void
    {
        $exporter = new TypeScriptSchemaExporter;

        $output = $exporter->export([]);

        $this->assertStringContainsString('export const apiSchema = {} as const;', $output);
    }

    public function test_emits_resource_entries_keyed_by_slug_with_sorted_top_level_keys(): void
    {
        $exporter = new TypeScriptSchemaExporter;

        $output = $exporter->export([
            'posts' => [
                'resource' => 'posts',
                'path' => '/api/v1/posts',
                'filters' => [
                    'status' => ['operators' => ['equal'], 'values' => ['open', 'closed']],
                ],
                'sorts' => ['created_at'],
                'includes' => ['author'],
                'fields' => ['posts' => ['title']],
                'appends' => ['posts' => ['excerpt']],
                'defaultSort' => '-created_at',
                'defaultFilters' => ['status' => 'open'],
            ],
            'comments' => [
                'resource' => 'comments',
                'path' => '/api/v1/comments',
                'filters' => [],
                'sorts' => [],
                'includes' => [],
                'fields' => [],
                'appends' => [],
            ],
        ]);

        // Top-level keys sorted alphabetically ('comments' before 'posts') regardless of input order.
        $commentsPos = strpos($output, "'comments': {");
        $postsPos = strpos($output, "'posts': {");

        $this->assertNotFalse($commentsPos);
        $this->assertNotFalse($postsPos);
        $this->assertLessThan($postsPos, $commentsPos);

        $this->assertStringContainsString("resource: 'posts',", $output);
        $this->assertStringContainsString("path: '/api/v1/posts',", $output);
        $this->assertStringContainsString("'status': { operators: ['equal'], values: ['open', 'closed'] },", $output);
        $this->assertStringContainsString("sorts: ['created_at'],", $output);
        $this->assertStringContainsString("includes: ['author'],", $output);
        $this->assertStringContainsString("fields: {\n      'posts': ['title'],\n    },", $output);
        $this->assertStringContainsString("appends: {\n      'posts': ['excerpt'],\n    },", $output);
        $this->assertStringContainsString("defaultSort: '-created_at',", $output);
        $this->assertStringContainsString("defaultFilters: {\n      'status': 'open',\n    },", $output);

        $this->assertStringContainsString('filters: {},', $output);
        $this->assertStringContainsString('sorts: [],', $output);
    }

    public function test_output_has_balanced_braces_and_brackets(): void
    {
        $exporter = new TypeScriptSchemaExporter;

        $output = $exporter->export([
            'posts' => [
                'resource' => 'posts',
                'path' => '/api/v1/posts',
                'filters' => ['status' => ['operators' => ['equal'], 'values' => ['open', 'closed']]],
                'sorts' => ['created_at'],
                'includes' => ['author', 'tags'],
                'fields' => ['posts' => ['title']],
                'appends' => ['posts' => ['excerpt']],
                'defaultSort' => '-created_at',
                'defaultFilters' => ['status' => 'open'],
            ],
        ]);

        $this->assertSame(substr_count($output, '{'), substr_count($output, '}'));
        $this->assertSame(substr_count($output, '['), substr_count($output, ']'));
        $this->assertSame(substr_count($output, '<'), substr_count($output, '>'));
    }
}
