<?php

namespace OpenSoutheners\LaravelApiable\Documentation\Exporters;

use OpenSoutheners\LaravelApiable\Documentation\EndpointSchemaGenerator;

/**
 * Renders the raw endpoint schema map produced by {@see EndpointSchemaGenerator}
 * into a single TypeScript module: the frozen `EndpointSchema` interface plus an `apiSchema`
 * const object keyed by JSON:API resource type slug, consumed by the flex-url v2 typed
 * generic (`flexUrl<typeof apiSchema.issues>(...)`).
 *
 * This does not implement {@see ExporterInterface} — that contract fans a `Resource[]`
 * documentation tree out to one-file-per-format, while this exporter always emits a single
 * TypeScript file from a resource-slug-keyed schema map.
 */
class TypeScriptSchemaExporter
{
    /**
     * The `EndpointSchema` interface, frozen to match the flex-url v2 TypeScript consumer.
     *
     * Deviation from the originally proposed union: `AllowedFilter::EXACT` serialises to
     * `equal` on the wire (`filter[attr][equal]=value`, see `AllowedFilter::operatorKey()`),
     * not `eq` — the union below uses `equal` to stay truthful to what the request parser
     * actually accepts.
     */
    private const INTERFACE_BLOCK = <<<'TS'
export interface EndpointSchema {
  resource: string;
  path: string;
  filters: Record<string, { operators: Array<'equal' | 'not_equal' | 'like' | 'not_like' | 'gt' | 'gte' | 'lt' | 'lte' | 'scope'>; values?: string[] }>;
  sorts: string[];
  includes: string[];
  fields: Record<string, string[]>;
  appends: Record<string, string[]>;
  defaultSort?: string;
  defaultFilters?: Record<string, string>;
}
TS;

    /**
     * @param  array<string, array<string, mixed>>  $schemas  Resource slug => EndpointSchema-shaped array.
     */
    public function export(array $schemas): string
    {
        ksort($schemas);

        $entries = [];

        foreach ($schemas as $slug => $schema) {
            $entries[] = $this->indent(1).$this->encodeKey((string) $slug).': '.$this->encodeSchema($schema).',';
        }

        $body = empty($entries) ? '{}' : "{\n".implode("\n", $entries)."\n}";

        return implode("\n", [
            '// generated by apiable:types — do not edit',
            '',
            self::INTERFACE_BLOCK,
            '',
            "export const apiSchema = {$body} as const;",
            '',
        ]);
    }

    /**
     * @param  array<string, mixed>  $schema
     */
    private function encodeSchema(array $schema): string
    {
        $lines = [];
        $lines[] = $this->indent(2)."resource: {$this->encodeString((string) $schema['resource'])},";
        $lines[] = $this->indent(2)."path: {$this->encodeString((string) $schema['path'])},";
        $lines[] = $this->indent(2)."filters: {$this->encodeFilters((array) $schema['filters'], 2)},";
        $lines[] = $this->indent(2)."sorts: {$this->encodeStringList((array) $schema['sorts'])},";
        $lines[] = $this->indent(2)."includes: {$this->encodeStringList((array) $schema['includes'])},";
        $lines[] = $this->indent(2)."fields: {$this->encodeStringListMap((array) $schema['fields'], 2)},";
        $lines[] = $this->indent(2)."appends: {$this->encodeStringListMap((array) $schema['appends'], 2)},";

        if (isset($schema['defaultSort'])) {
            $lines[] = $this->indent(2)."defaultSort: {$this->encodeString((string) $schema['defaultSort'])},";
        }

        if (! empty($schema['defaultFilters'])) {
            $lines[] = $this->indent(2)."defaultFilters: {$this->encodeStringMap((array) $schema['defaultFilters'], 2)},";
        }

        return "{\n".implode("\n", $lines)."\n".$this->indent(1).'}';
    }

    /**
     * @param  array<string, array{operators: list<string>, values?: list<string>}>  $filters
     */
    private function encodeFilters(array $filters, int $indentLevel): string
    {
        if (empty($filters)) {
            return '{}';
        }

        ksort($filters);

        $pad = $this->indent($indentLevel + 1);
        $lines = [];

        foreach ($filters as $attribute => $entry) {
            $parts = ['operators: '.$this->encodeStringList($entry['operators'])];

            if (! empty($entry['values'])) {
                $parts[] = 'values: '.$this->encodeStringList($entry['values']);
            }

            $lines[] = $pad.$this->encodeKey((string) $attribute).': { '.implode(', ', $parts).' },';
        }

        return "{\n".implode("\n", $lines)."\n".$this->indent($indentLevel).'}';
    }

    /**
     * @param  array<string, list<string>>  $map
     */
    private function encodeStringListMap(array $map, int $indentLevel): string
    {
        if (empty($map)) {
            return '{}';
        }

        ksort($map);

        $pad = $this->indent($indentLevel + 1);
        $lines = [];

        foreach ($map as $key => $values) {
            $lines[] = $pad.$this->encodeKey((string) $key).': '.$this->encodeStringList($values).',';
        }

        return "{\n".implode("\n", $lines)."\n".$this->indent($indentLevel).'}';
    }

    /**
     * @param  array<string, string>  $map
     */
    private function encodeStringMap(array $map, int $indentLevel): string
    {
        if (empty($map)) {
            return '{}';
        }

        ksort($map);

        $pad = $this->indent($indentLevel + 1);
        $lines = [];

        foreach ($map as $key => $value) {
            $lines[] = $pad.$this->encodeKey((string) $key).': '.$this->encodeString((string) $value).',';
        }

        return "{\n".implode("\n", $lines)."\n".$this->indent($indentLevel).'}';
    }

    /**
     * @param  list<string>  $list
     */
    private function encodeStringList(array $list): string
    {
        if (empty($list)) {
            return '[]';
        }

        return '['.implode(', ', array_map(fn ($value) => $this->encodeString((string) $value), $list)).']';
    }

    private function encodeKey(string $key): string
    {
        return $this->encodeString($key);
    }

    private function encodeString(string $value): string
    {
        $escaped = str_replace(
            ['\\', "'", "\n", "\r"],
            ['\\\\', "\\'", '\\n', '\\r'],
            $value
        );

        return "'{$escaped}'";
    }

    private function indent(int $level): string
    {
        return str_repeat('  ', $level);
    }
}
